In [1]:
################## ALIŞTIRMALAR ###################### 

In [2]:
import numpy as np

In [3]:
#Bölüm 1

5 tane 1 barındıran bir array oluşturun

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun

In [5]:
arr = np.arange(2,100,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5 tane 10 bulunan bir array oluşturun

In [6]:
arr = np.ones(5) * 10
arr

array([10., 10., 10., 10., 10.])

veya

In [7]:
arr = np.zeros(5) + 10
arr

array([10., 10., 10., 10., 10.])

1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun

In [8]:
arr = np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

4x4'lük bir birim matris oluşturun

In [9]:
arr = arr.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

4x4'lük bir birim matris oluşturun

In [10]:
arr = np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
0 ile 5 arasında rastgele değerler üretin

SyntaxError: invalid syntax (2844281226.py, line 1)

In [ ]:
x = np.random.rand() * 5
x

5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

In [ ]:
arr = np.random.randn(5,5)
arr

1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

In [ ]:
arr = np.linspace(1,5,20)
arr

In [ ]:
#Bölüm 2

In [ ]:
arr = np.arange(1,101).reshape(10,10)
arr

In [ ]:
arr[4:,]
# arr[4:,:] da aynı şey

In [ ]:
arr[4:,4:]

In [ ]:
arr[0:3,2:4]

In [ ]:
arr[:3,1]

In [ ]:
arr[:3,1].reshape(3,1)

In [ ]:
arr[:,9]

In [ ]:
#Bölüm 3

In [ ]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)


In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr1+ arr2

In [ ]:
arr1*arr2

In [ ]:
np.mean(arr1)

In [ ]:
np.sum(arr1)