In [1]:
import numpy as np


In [3]:
arr = np.arange(1,10)

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[1]

2

In [7]:
arr[1:5]

array([2, 3, 4, 5])

In [9]:
arr[:4]

array([1, 2, 3, 4])

In [10]:
arr[::2]

array([1, 3, 5, 7, 9])

In [11]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[:3]

array([1, 2, 3])

In [15]:
arr[:3] = 25
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [16]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr2 = arr
arr2[:3] = 100


In [20]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [21]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

arr2'yi arr ye atadım, arr2 dizisinde ben değişiklik yapacağım, yaptığım değişiklik arr'ye de yansıyacak.
Bunun sebebi, bir numpy arrayi olusturduk ve bu arr değişkenimiz bu adresi gösteriyor, arr2=arr yapıldığında arr2 de yine
aynı adresi gösterecek.Böylelikle arr2'de yapacağım değişiklikler arr'yi de etkiliyor

Copy metodu ile birinde yapacağım değişiklil diğerine yansımayacak

In [22]:
arr = np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr2 = arr.copy()
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr2[:3] = 30
arr2

array([30, 30, 30,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
newArray = np.arange(1,21)
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [30]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
newArray = newArray.reshape(5,4)
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [32]:
newArray[0,1]

2

In [40]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

ilk kısım yani ( [: , ) kısmında eğer hatırlarsan [:] metodu ile baştan sona hepsini alıyorduk,
bu yüzden yine baştan sona hepsi için geçerli olacak,
ikinci kıssım yani ( ,:2] ) kısmı ise eğer hatırlarsan [:2] metodu ile baştan 2. indise kadar
almamızı sağlıyordu
birleştirince de bu şekil bir matris oluşturabildik

kafan eğer karışırsa başlangıç kısma [: demek yerine [0: da diyebilirsin.

In [42]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [43]:
newArray[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [49]:
newArray[0:2,0:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
newArray[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
####         ARRAY FİLTRELEME      #####

In [54]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [56]:
booleanArray = arr > 3
arr[booleanArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[arr>6]

array([ 7,  8,  9, 10])

In [93]:
### Numpy'dan dolayi değil , dizilerde dizi2 yi değiştirdikten sonra dizi1'de yine değişecektir
### bunu çözmek için copy meteodunu kullanacağız!

## Numpy kullanmakta şöyle bir fayda var, dizi2[2:5] = 30 yaptığımda dizi2'nin 2,3,4 indexlerinin değerleri
## 30 oluyor yani 1,2,30,30,30,6,7,8,9,10 oluyor
## Kullanmazsam eğer dizi2[2:5] = 30 yapamıyorum ,  dizi2[2:5] = 30,30,30 yapmam gerekiyor


In [94]:
dizi1 = [1,2,3,4,5,6,7,8,9,10]
dizi2 = dizi1.copy()

In [95]:
dizi2


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [96]:
dizi2[2]

3

In [97]:
dizi2[2:5]

[3, 4, 5]

In [101]:
dizi2[2:5] = 30,30,30

In [102]:
dizi2

[1, 2, 30, 30, 30, 6, 7, 8, 9, 10]

In [103]:
dizi1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [104]:
dizi3 = np.arange(1,11)
dizi3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
dizi4 = dizi3.copy()
dizi4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
dizi4[2:5]

array([3, 4, 5])

In [107]:
dizi4[2:5] = 30

In [108]:
dizi4

array([ 1,  2, 30, 30, 30,  6,  7,  8,  9, 10])