In [1]:
data_list = [1,2,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(data_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
dataList2=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr2 = np.array(dataList2)

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr3 = np.array([1,2,3])
arr3

array([1, 2, 3])

In [10]:
arr3[2]

3

In [11]:
arr2[2,1]

8

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

np.arange metodu, array'ler üzerinde range metodunu uygulayabildiğimizi gösteriyor

In [13]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

2,2 'lik bir sıfır matrisi oluşturur.

In [17]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

linspace metodu ile 0'dan 100'e kadar olan sayıları 5 eşit parçaya böldük.

In [19]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Birim matris oluşturmamızı sağlıyor,diagonal'ler yani köşeler hep 1 oluyor

In [21]:
np.random.randint(0,10)

4

0 ile 10 arasinda rastgele bir int sayı döndürür

In [22]:
np.random.randint(15)

5

In [23]:
np.random.randint(0,50,6)

array([28, 23, 13, 34, 26, 27])

0-50 arası 6 tane değer üret ve array'e depola.

In [24]:
np.random.rand(4)

array([0.23669649, 0.86322072, 0.20667065, 0.26248053])

In [25]:
np.random.rand(4) * 10

array([4.19454427, 1.57095592, 6.96468876, 8.17830133])

In [26]:
np.random.randn(5)

array([ 0.66680171,  0.07044216, -2.21563592,  1.28823439,  1.50086068])

randn ile 0'ın etrafında Gauss Distribution yapılır.

In [27]:
arr5 = np.arange(25)

In [28]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr5.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

reshape ile 5,5 lik matris oluşturdum,
25 değer olduğunu için arr5.reshape(4,5) gibi bir şey yapılamaz.

In [30]:
newArray = np.random.randint(0,10,5)
newArray

array([8, 4, 4, 2, 8])

In [31]:
newArray.max()

8

In [32]:
newArray.min()

2

In [33]:
newArray.sum()

26

In [34]:
newArray.mean()

5.2

In [35]:
newArray.argmax()
# max deger hangi indexte

0

In [36]:
newArray.argmin()
# min deger hangi indexte

3

In [37]:
detArray = np.random.randint(1,100,10)

In [38]:
detArray

array([50, 17, 27, 34, 16, 91, 69, 17, 60, 49])

In [39]:
detArray2 = np.array([[1,2],[3,4]])
detArray2

array([[1, 2],
       [3, 4]])

In [40]:
np.linalg.det(detArray2)

-2.0000000000000004

In [41]:
round(-2.0000000000000004)

-2