In [1]:
################## ALIŞTIRMALAR ###################### 

In [2]:
import numpy as np

In [3]:
#Bölüm 1

5 tane 1 barındıran bir array oluşturun

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun

In [5]:
arr = np.arange(2,100,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5 tane 10 bulunan bir array oluşturun

In [6]:
arr = np.ones(5) * 10
arr

array([10., 10., 10., 10., 10.])

veya

In [7]:
arr = np.zeros(5) + 10
arr

array([10., 10., 10., 10., 10.])

1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun

In [8]:
arr = np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

4x4'lük bir birim matris oluşturun

In [9]:
arr = arr.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

4x4'lük bir birim matris oluşturun

In [10]:
arr = np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

0 ile 5 arasında rastgele değerler üretin

In [11]:
x = np.random.rand() * 5
x

2.0965806148802173

5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

In [12]:
arr = np.random.randn(5,5)
arr

array([[ 0.98490617, -1.40669533, -0.13829   , -0.71645059,  1.75080106],
       [-0.94463104,  0.89104829, -0.51567297,  0.61706858, -0.07038186],
       [-0.62093027, -0.33807907, -0.43481588, -1.18299936,  0.49488543],
       [ 1.06972655,  0.44723696, -1.31598294,  0.21739135, -0.47809126],
       [ 2.11052032, -2.20595727,  0.72773376, -0.60897437, -1.18466309]])

1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

In [13]:
arr = np.linspace(1,5,20)
arr

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [14]:
#Bölüm 2

In [15]:
arr = np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [16]:
arr[4:,]
# arr[4:,:] da aynı şey

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [17]:
arr[4:,4:]

array([[ 45,  46,  47,  48,  49,  50],
       [ 55,  56,  57,  58,  59,  60],
       [ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [18]:
arr[0:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [19]:
arr[:3,1]

array([ 2, 12, 22])

In [20]:
arr[:3,1].reshape(3,1)

array([[ 2],
       [12],
       [22]])

In [21]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [22]:
#Bölüm 3

In [23]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)


In [24]:
arr1

array([[4, 3, 2],
       [1, 4, 1],
       [3, 0, 2]])

In [25]:
arr2

array([[1, 1, 3],
       [1, 4, 0],
       [1, 2, 1]])

In [26]:
arr1+ arr2

array([[5, 4, 5],
       [2, 8, 1],
       [4, 2, 3]])

In [27]:
arr1*arr2

array([[ 4,  3,  6],
       [ 1, 16,  0],
       [ 3,  0,  2]])

In [28]:
np.mean(arr1)

2.2222222222222223

In [29]:
np.sum(arr1)

20