In [1]:
import numpy as np

In [4]:
arr1 = np.arange(10,61,10)
arr1

array([10, 20, 30, 40, 50, 60])

In [7]:
arr2 = np.arange(2,8)
arr2

array([2, 3, 4, 5, 6, 7])

In [8]:
arr1 + arr2

array([12, 23, 34, 45, 56, 67])

eleman sayilari eşit olmazsa hata verecektir

In [9]:
arr1 - arr2

array([ 8, 17, 26, 35, 44, 53])

In [10]:
arr1 * arr2

array([ 20,  60, 120, 200, 300, 420])

In [12]:
arr1

array([10, 20, 30, 40, 50, 60])

In [13]:
arr1 + 10

array([20, 30, 40, 50, 60, 70])

In [14]:
arr2

array([2, 3, 4, 5, 6, 7])

In [15]:
arr2-5

array([-3, -2, -1,  0,  1,  2])

In [16]:
arr1 / 5

array([ 2.,  4.,  6.,  8., 10., 12.])

In [17]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

In [18]:
# Numpy'ın kalan fonksiyonlarına numpy documentation'dan bakabilirsin

In [95]:
################## ALIŞTIRMALAR ###################### 

In [94]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
arr = np.arange(2,100,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [24]:
arr = np.ones(5) * 10
arr

array([10., 10., 10., 10., 10.])

In [25]:
arr = np.zeros(5) + 10
arr

array([10., 10., 10., 10., 10.])

In [26]:
arr = np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [28]:
arr = arr.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
arr = np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
x = np.random.rand() * 5
x

4.600803543247924

In [70]:
arr = np.random.randn(5,5)
arr

array([[ 0.39067893, -1.2469653 , -0.0798466 , -1.65762468,  0.30446221],
       [-0.39618623,  0.54414422, -1.12965529, -0.04571178, -1.1880813 ],
       [ 1.71532862, -1.41942131, -0.31494172,  1.53410143, -0.4306909 ],
       [-0.12832146,  0.90447579,  0.0812581 ,  1.83589226, -1.74459139],
       [ 1.10057477,  0.70929335, -0.8332487 ,  0.19093933, -1.12060647]])

In [68]:
arr = np.linspace(1,5,20)
arr

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
import numpy as np

In [11]:
arr = np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [21]:
arr[4:,]
# arr[4:,:] da aynı şey

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [13]:
arr[4:,4:]

array([[ 45,  46,  47,  48,  49,  50],
       [ 55,  56,  57,  58,  59,  60],
       [ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [14]:
arr[0:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [15]:
arr[:3,1]

array([ 2, 12, 22])

In [16]:
arr[:3,1].reshape(3,1)

array([[ 2],
       [12],
       [22]])

In [17]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [87]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)


In [88]:
arr1

array([[2, 2, 0],
       [4, 0, 4],
       [4, 2, 1]])

In [89]:
arr2

array([[3, 0, 3],
       [1, 3, 1],
       [0, 2, 0]])

In [90]:
arr1+ arr2

array([[5, 2, 3],
       [5, 3, 5],
       [4, 4, 1]])

In [91]:
arr1*arr2

array([[6, 0, 0],
       [4, 0, 4],
       [0, 4, 0]])

In [92]:
np.mean(arr1)

2.111111111111111

In [93]:
np.sum(arr1)

19